const plantList = [
  "Lipstick",
  "Delta maidenhair",
  "Silver vase",
  "Century plant",
  "Coral berry",
  "Autralian maidenhair",
  "Amelia",
  "Painted Princess",
  "Queen of Siam",
  "Jewel of India",
  "Patricia",
  "Green Lady",
  "Black Lance",
  "Silver Queen",
  "Rapsody in Green",
  "Manila Pride",
  "Emerald Beauty",
  "Jubilee",
  "Abidjan",
  "Maria Chirstina",
  "Elephant ear",
  "Emerald Isle",
  "Mary Ann",
  "Golden Trumpet",
  "BJ Freeman",
  "Marguerita",
  "Emerald Star",
  "Silver Bay",
  "Cast iron plant",
  "Bronze Anthurium",
  "Fish tail palm",
  "Croton",
  "Tree Cereus",
  "Dwarf tree fern",
  "Neanthebella palm",
  "Medallion Calathea",
  "Silver Calathea",
  "Paper flower",
  "Reed Palm",
  "Wax flower",
  "Cabbage Anthurium",
  "Ellen Danica",
  "Monster cactus",
  "Bamboo palm",
  "Stromante",
  "Velvet Calathea",
  "Jade Plant",
  "Grape Ivy",
  "Steel palm",
  "Aspidistra Milky Way",
  "Stiped calathea",
  "Birdnest fern",
  "Spider plant",
  "Tree Maindenhair fern",
  "Tropic Mary Ann",
  "Star Bright",
  "Tricolor",
  "Cornstalk plant",
  "Janet Craig",
  "Song of India",
  "Carina",
  "Song of Jamaica",
  "King sago",
  "Phrynium",
  "Malaysian Dracaena",
  "Gold Star",
  "Holly-fern",
  "Calypso Queen",
  "Squirrels foot",
  "Lisa",
  "Madagascar dragon tree",
  "Warneckei",
  "Lemon Lime",
  "Camille",
  "Tropic Snow",
  "Tineke",
  "Butterfly palm",
  "Orchid cactus",
  "Golden Barrel",
  "Crown of thorns",
  "Marble Queen",
  "Guzmania Sunnytime",
  "Amstel King",
  "Guzmania Empire",
  "Weeping fig",
  "Japanese Aralia",
  "Variegated Euphorbia",
  "Curl",
  "Claret",
  "Robusta",
  "Montgomery ivy",
  "Golden Pothos",
  "Fidleleaf fig",
  "Giant Candelabra tree",
  "Monique",
  "Mariposa",
  "Willow Ficus",
  "Marjan",
  "Midnight",
  "Rana",
  "Burgandy",
  "Gold Baby",
  "Pink praying plant",
  "Hermania",
  "Mexican Breadfruit",
  "Pepper face",
  "Snakes beard",
  "White Ginger",
  "Variegated English ivy",
  "Garland",
  "Wax plant",
  "Rose bay",
  "Madagascar Palm",
  "Spiny licuala palm",
  "Imperial Red",
  "Variegated lily turf",
  "Velvet leaf vine",
  "Herringbone",
  "Pony tail",
  "Moonlight",
  "Spindle palm",
  "English ivy",
  "Rose grape",
  "Chinese hibiscus",
  "Sword fern",
  "Paradise palm",
  "Emerald Prince",
  "Emerald Gem",
  "Tricolor Peperomia",
  "Bower of beauty",
  "China doll",
  "Cretan brake",
  "Tsu sima holly fern",
  "Japanese tassel fern",
  "Majesty palm",
  "Red Aralia",
  "Silver Ribbon Fern",
  "Staghorn fern",
  "Aralia Balfouriana",
  "Snake plant",
  "Fernleaf Philodendron",
  "Buddhist pine",
  "Chicken gizard aralia",
  "Pignee Date palm",
  "Parsley panax",
  "Lacy tree philodendron",
  "Silver Lace Fern",
  "Lady palm",
  "Sweetheart plant",
  "Christmas palm",
  "Peace lily",
  "Christmas bells",
  "Arrowhead vine",
  "Parrot palm",
  "Pink quill",
  " Indian kale",
  "False aralia",
  "Burro tail",
  "Satin pothos",
  "Grass tree",
  "Yellow parasol plant",
  "Umbella plant",
  "Parasol plant",
  "Emerald Swirl",
  "White bird of paradise",
  "Zz plant",
  "Palm lily"
]

export default plantList;